# Configuration for object generation
model_name: ""
keys_path: "configs/keys.yaml"
output_file: "assets/objects.json"
category_file: "assets/categories.json"
objects_per_category: 50
system_prompt: ""
max_concurrent_per_key: 300
max_retries: 5
